language: go
go:
 - 1.1
 - 1.2
 - 1.3
 - 1.4
 - 1.5
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get -v ./smsaero
script:
  - if [ "$TRAVIS_GO_VERSION" == "1.5" ]; then go test -v ./smsaero -covermode=count -coverprofile=coverage.out; fi
  - if [ "$TRAVIS_GO_VERSION" == "1.5" ]; then $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
